apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gtlrvpxpy-python-gitops
  description: This is GitOps manifest for gtlrvpxpy-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=gtlrvpxpy-python
    backstage.io/kubernetes-id: gtlrvpxpy-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gtlrvpxpy-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gtlrvpxpy-python
